# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FMYGirl9' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FMYGirl9

   pod 'MBProgressHUD', '~> 1.0.0'




end

